### PR TITLE
Add secret command to input GitHub/GitLab token on onboarding

### PR DESCRIPTION
**Pull request by dherault**
## Summary

So, 
This PR create a secret token management flow for the onboarding.

How to use:
1 - Go to app.plural.sh and start the onboarding, after you've clicked on GitHub/GitLab and been redirected, 
type `t o k e n o u t`. 
The token should appear in an old-fashioned alert.
2 - Go to your dev/staging env. 
At the start of the onboarding type `t o k e n i n` 
(be careful of the applications search bar input autofocus) 
and input your token in the appearing prompt.
3 - You can now go through the onboarding with your updated token.
4 - Remember: the token expires after some time.

Also:
- The file `debug-tokens` is gone.
- I fixed a react keys warning on Router

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [x] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
Could we make the key sequence more memorable (it's not like it's actually a secret).  Perhaps something like "g i t t o k e n"

**Comment by dherault** [comment]
We need two sequences, what do you suggest?

**Comment by floreks** [comment]
We actually don't need 2 sequences. It is easier to generate token directly on the GitHub page. Token can be granted only specific permissions. We could also maybe use growthbook to enable this workaround for us instead of having to remember the sequence.

**Comment by michaeljguarino** [comment]
It couldn't be like `gittoken out` and `gittoken in` as the sequences?  I don't think the one you chose is that hard to remember either, if we were to use it

**Comment by dherault** [comment]
New sequences in description.

**Comment by dherault** [comment]
I still think we need two sequences because it may be hard for the design team to go to github and issue a token. Hard but feasible ofc.

**Review by maciaszczykm — APPROVED** [review]

**Pull request merged**
