### PR TITLE
feat: Expose selected region via shell configuration workspace

### PR DESCRIPTION
**Pull request by floreks**
## Summary

Since `updateShell` mutation will only allow to update `credentials` struct, we will need to expose the region that can be shown in the UI. It will not be editable.

Ref: [figma](https://www.figma.com/file/985LCDEqp4ckoMLOHSWkDF/Onboarding-v3?node-id=209%3A51675&t=ZtoQFtURUFRGYXLM-4)
image

## Test Plan

Updated unit test

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Review by michaeljguarino — APPROVED** [review]
This is returned in the cli api request right?  We might need another pr if not

**Comment by michaeljguarino** [comment]
You can also get this from the cloud shell object itself btw (I think).  We probably shouldn't make it editable in general since it could really screw with stuff.

**Comment by floreks** [comment]
Unfortunately, neither shell nor shell configuration queries expose this information right now.

**Comment by michaeljguarino** [comment]
> Unfortunately, neither shell nor shell configuration queries expose this information right now.

ah we kept it out of the graphql response? We can expose it on the shell query i think, it's not sensitive info (other stuff is hidden for obv reasons)

**Comment by floreks** [comment]
> > Unfortunately, neither shell nor shell configuration queries expose this information right now.
> 
> ah we kept it out of the graphql response? We can expose it on the shell query i think, it's not sensitive info (other stuff is hidden for obv reasons)

Exactly, it was defined in the model, but not exposed via shell query response. It should be safe to expose it as read-only information. I agree that we should definitely not allow to change it.

**Pull request merged**
