### PR TITLE
Add configure my cloud functionality

### PR DESCRIPTION
**Pull request by maciaszczykm**
## Summary
It adds "configure my cloud" button to all GCP demo cloud shells. After confirmation demo project is deleted and user is redirected back to onboarding.

Closes ENG-652.

## Test Plan
Tested manually.

## Checklist
- [x] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [x] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@dherault Not sure why but even after https://github.com/pluralsh/design-system/pull/226 it doesn't work but when I put design system props directly in the app everything is fine. PTAL.

**Review by dherault — APPROVED** [review]
👍

**Comment by dogmar** [comment]
Does this still show up for people who used their own cloud credentials? Should it?

**Comment by maciaszczykm** [comment]
@dogmar It should show only to the users using GCP cloud demo project. I've used `POLL_DEMO_PROJECT_QUERY ` to check if that's the case.That's what it should look like in other cases:

Zrzut ekranu 2022-10-20 o 09 45 02

**Comment by dogmar** [comment]
Oh I see that now. Sorry I was looking in the wrong spot for a check. LGTM.

**Review by dogmar — APPROVED** [review]

**Comment by maciaszczykm** [comment]
Sure, np.

**Pull request merged**
