### PR TITLE
ENG-480 - Update login view and skip demo button styling

### PR DESCRIPTION
**Pull request by floreks**
## Summary

As per [linear comment](https://linear.app/pluralsh/issue/ENG-480/update-design-on-auth-landing-pages#comment-deae546e).

I have also fixed the responsiveness issues with the login view.

**NOTE:** Our current plural logo (icon + text) has a very small gap. Do we have anything else or should it stay as is?
image

image

## Test Plan

Locally (also checked the responsive layout)

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

### CODE REVIEW

**Review by maciaszczykm — APPROVED** [review]

**Comment by floreks** [comment]
@pluralsh/design PTAL

**Comment by michaeljguarino** [comment]
Is it possible to make this pr against master so we can release it sooner?

**Comment by floreks** [comment]
It would require a quite significant portion of the `packages-redesign` branch to be merged into master. There are lots of changes related to the design system itself that have a global impact on the application and this PR requires the latest version of the design system.

**Review by dherault — APPROVED** [review]

**Comment by michaeljguarino** [comment]
Hey @floreks I think we should drop the text size for both the header and description on the value props at least one more level

**Comment by cris-dobbins** [comment]
@floreks Can you make the titles "Subtitle 1" 20px, and the body copy "Body 2" 14px. Check mark bullet points should be 16px. Also can you update the Plural logo to our current logo. Design is in [figma here](https://www.figma.com/file/rCCFdkFyrfdcr7nCwetYOk/Onboarding-Experience?node-id=1225%3A36213) and the most current logo is [here](https://www.figma.com/file/xTahKNBAj2LQbrTsj4nuaq/Marketing-Design-System?node-id=33%3A18). Trying to get that current logo updated everywhere. Also can you make the Plural logo link to https://www.plural.sh/?

**Comment by floreks** [comment]
The logo will be updated once it gets merged into the design system.

**Review by michaeljguarino — APPROVED** [review]

**Pull request merged**
