### PR TITLE
Updated Readme file

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
## Summary

Removed redundant bullets mark in documentation section of the Readme file.

## Labels

`enhancement`

### CODE REVIEW

**Review by michaeljguarino — APPROVED** [review]

**Comment by SaptarshiSarkar12** [comment]
@michaeljguarino why are the two ci checks failing?

**Comment by SaptarshiSarkar12** [comment]
@michaeljguarino please merge this PR.

**Review by dherault — APPROVED** [review]

**Review by michaeljguarino — APPROVED** [review]

**Comment by michaeljguarino** [comment]
Sorry about that, I think the firebase ci only works for users w/in our org

**Comment by SaptarshiSarkar12** [comment]
Its okay. 
I have understood @michaeljguarino .

**Pull request merged**
